version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vue"
        versions: ["3.x"]
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "weekly"
